apiVersion: v2
appVersion: "1.0"
description: A Helm chart for fact-admin App
name: fact-admin
home: https://github.com/hmcts/fact-admin
version: 0.0.24
dependencies:
  - name: nodejs
    version: 2.4.14
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
  - name: idam-pr
    version: 2.4.14
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: idam-pr.enabled

