apiVersion: v2
appVersion: "1.0"
description: A Helm chart for fact-admin App
name: fact-admin
home: https://github.com/hmcts/fact-admin
version: 0.0.34
dependencies:
  - name: nodejs
    version: 3.2.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
